version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/src/hydra_core"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/src/hydra-core"
  schedule:
    interval: "daily"
