version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
  directory: "/src/hydra-core"
  schedule:
    interval: "weekly"

- package-ecosystem: "npm"
  directory: "/src/hydra-ui"
  schedule:
    interval: "monthly"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  

