# Generated by Django 4.0.1 on 2022-01-11 02:37

from django.db import migrations, models, transaction
from django.utils import timezone
from django_add_default_value import AddDefaultValue


@transaction.atomic
def approve_past_records(apps, schema_editor):
    TimeRecord = apps.get_model('time_reporting', "TimeRecord")
    now = timezone.now()
    queryset = TimeRecord.objects.filter(start_time__lte=now).select_for_update()
    for record in queryset:
        record.approved = True
    TimeRecord.objects.bulk_update(queryset, ["approved"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('time_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        AddDefaultValue(
            model_name="timerecord",
            name="approved",
            value=True,
        ),
        migrations.RunPython(approve_past_records),
    ]
