[tool.black]
line-length = 79
target-version = ['py39']
exclude = "/(migrations|env)/"

[tool.isort]
profile = "black"
line_length = 79
skip = ["env"]
skip_glob = ["src/*/migrations"]

force_sort_within_sections = true
order_by_type = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "hydra_core.settings"
python_files = "tests.py test_*.py"
addopts = "--verbose --ignore=env -r s"
