#!groovy

pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/podTemplate.yaml'
            defaultContainer 'docker'
        }
    }

    parameters {
        booleanParam(name: 'CHECK', defaultValue: true, description: 'Run source code linters')
        booleanParam(name: 'TEST', defaultValue: true, description: 'Run unit tests')
        booleanParam(name: 'BUILD_IMAGES', defaultValue: env.BRANCH_NAME=="master", description: 'Build container images')
	    string(name:'IMAGE_TAG', defaultValue: (env.BRANCH_NAME=="master"? 'latest': env.BRANCH_NAME), description: "Docker image tag")
    }

    environment {
        REPO_NAME = "hydra"
        REGISTRY = "registry.anthonyoteri.com"
        DATE_TAG = java.time.LocalDate.now()
    }

    options {
        ansiColor('xterm')
    }

    stages {

        stage('Dependencies') {
            when {
                expression { params.CHECK || params.TEST }
            }

            steps {
                container('python') {
                    dir('src/hydra_core') {
                        sh "pip3 install -r requirements.txt"
                        sh "pip3 install -e ."
                    }
                }
            }
        }

        stage('Check') {

            when {
                expression { params.CHECK }
            }
            
            parallel {
                stage('Lint (pylint)') {
                    steps {
                        container('python') {
                            dir('src/hydra_core') {
                                sh "pylint time_reporting hydra_core"
                            }
                        }
                    }
                }
                stage('Lint (flake8)') {
                    steps {
                        container('python') {
                            dir('src/hydra_core') {
                                sh "flake8"
                            }
                        }
                    }
                }
                stage('Lint (mypy)') {
                    steps {
                        container('python') {
                            dir('src/hydra_core') {
                                sh "mypy ." 
                            }
                        }
                    }
                }
                stage('Lint (black)') {
                    steps {
                        container('python') {
                            dir('src/hydra_core') {
                                sh "black --check ."
                            }
                        }
                    }
                }
                stage('Lint (isort)') {
                    steps {
                        container('python') {
                            dir('src/hydra_core') {
                                sh "isort --check ."
                            }
                        }
                    }
                }
                stage('Lint (migrations)') {
                    steps {
                        container('python') {
                            dir('src/hydra_core') {
                                sh "python manage.py makemigrations --dry-run --check"
                            }
                        }
                    }
                }
            }
        }

        stage('Test') {

            when {
                expression { params.TEST } 
            }

            steps {
	        
                container('python') {
                    dir('src/hydra_core') {
                        sh "pytest -rs --junit-xml=results.xml"
                        junit 'results.xml'
                    }
                }
            }
        }

        stage('Build images') {

            when {
                expression { params.BUILD_IMAGES }
            }

            steps {
                container('docker') {
                    sh "docker build -t ${REPO_NAME}:${DATE_TAG} ."
                }
            }
        }

        stage("Tag images") {

            when {
                expression { params.BUILD_IMAGES }
            }  

            steps {
                container('docker') {
                    sh "docker tag ${REPO_NAME}:${DATE_TAG} ${REGISTRY}/${REPO_NAME}:${DATE_TAG}-${BRANCH_NAME}"
                    sh "docker tag ${REPO_NAME}:${DATE_TAG} ${REGISTRY}/${REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage("Post images") {

            when {
                expression { params.BUILD_IMAGES }
            }

            steps {
                container('docker') {
                    sh "docker push ${REGISTRY}/${REPO_NAME}:${DATE_TAG}-${BRANCH_NAME}"
                    sh "docker push ${REGISTRY}/${REPO_NAME}:${IMAGE_TAG}"
                }
            }

        }
    }
}
