# Generated by Django 3.2.9 on 2021-11-10 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
