name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - etc
      - src
      - Dockerfile
      - .dockerignore
      - docker-entrypoint.sh

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.anthonyoteri.com/hydra:latest
    - name: Push the Docker image
      run: docker push registry.anthonyoteri.com/hydra:latest
