name: Hydra-UI
on:
  pull_request:
    paths:
      - 'src/hydra-ui/**'
jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/hydra-ui

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '17'
          registry-url: 'https://registry.yarnpkg.com'
          cache: 'npm'
          cache-dependency-path: 'src/hydra-ui/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier

      - name: Lint
        run: npx eslint --ext=.js,.jsx,.ts,.tsx --max-warnings=0 src

      - name: Test
        run: npm test --runInBand
        env:
          CI: 'true'

      - name: Compile
        run: npx tsc --noEmit
