name: Migration Compatibility
on:
  pull_request:
    paths:
      - "src/hydra-core/*/migrations/**"

jobs:
  hydra-core:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_DB: hydra
          POSTGRES_USER: hydra
          POSTGRES_PASSWORD: hydra
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: src/hydra-core

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: "src/hydra-core/requirements.txt"

      - name: Checkout latest tag
        run: git switch -d "$(git describe --match='v[0-9]*.[0-9]*.[0-9]*' --abbrev=0)"

      - name: Add migrations from master
        run: |
          git restore -s ${{ github.sha }} -- ./*/migrations
          git status -su -- ./*/migrations

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Install hydra-core
        run: pip install -e ./

      - name: Install pytest-github-actions-annotate-failures
        run: pip install pytest-github-actions-annotate-failures

      - name: Test
        run: pytest
        env:
          DATABASE_URL: postgres://hydra:hydra@localhost:5432/hydra
          SERIALIZE_TEST_DATABASE: "false"
